### ISSUE TITLE
Draw call is slow

### ISSUE THREAD

**Issue by tekgo** [Echorridoors/Babelium#1]
Display.draw() is making a bunch of changes to the dom in it's loop which is really slow. Causing draw calls to take upwards of a couple seconds on my machine.

A fix is to write to a buffer and change the display with a single assignment.

``` 
this.draw = function()
  {
    var buffer = "";
    for (l = LINES_PER_PAGE-1; l > -1; l--) { 
      for (c = 0; c < CHARACTERS_PER_LINE; c++) { 
        buffer += this.lines[l][c].draw();
      }
      buffer += "<br />";
    }
    this.element.innerHTML = buffer;
    this.keyboard.is_locked = false;
  }
```

**Comment by neauoire** [comment]
Awesome!
